import auth from './user.route';
import upload from './upload.route';
import electricity from './electricity.route';
import cabletv from './cabletv.route';
import airtime from './airtime.route';
import data from './data.route';
import admin from './admin.route';
import variation from './variation.route';
import wallet from './wallet.route';
import transaction from './transaction.route';
import fund from './fund.route';
import commissions from './commission.route';
import issue from './issue.route';
import referral from './referral.route';
import beneficiary from './beneficiary.route';
import paymentSecret from './paymentSecret.route';
import appUpdate from './appUpdate.route';
import message from './message.route';
import posTerminal from './posTerminal.route';
import aggregator from './aggregator.route';

export default (router) => {
  auth(router);
  upload(router);
  electricity(router);
  cabletv(router);
  airtime(router);
  data(router);
  admin(router);
  variation(router);
  wallet(router);
  transaction(router);
  fund(router);
  commissions(router);
  issue(router);
  referral(router);
  beneficiary(router);
  paymentSecret(router);
  appUpdate(router);
  message(router);
  posTerminal(router);
  aggregator(router);
};
