// @flow

/**
 * App constants
 */
exports.REFERRAL_BONUS = 50;
exports.COMMISSION_WITHDRAW_LIMIT = 500;
exports.POS_TERMINAL_TRANSACTION_LIMIT = 500000;

exports.POS_AGGREGATOR_COMMISSION_PERCENT = 0.05;

// OLD
exports.FUND_WALLET_CHARGE_AMOUNT = 50;
exports.FUND_WALLET_CHARGE_AMOUNT_AGENT = 0;
exports.FUND_WALLET_CHARGE_AMOUNT_SUPERAGENT = 0;

// NEW
// exports.FUND_WALLET_CHARGE_AMOUNT = 50;
// exports.FUND_WALLET_CHARGE_AMOUNT_AGENT = 50;
// exports.FUND_WALLET_CHARGE_AMOUNT_SUPERAGENT = 50;

exports.BVN_CHARGE = 20;
