export default [
  {
    "232": "STERLING BANK PLC",
    "bankName": "STERLING BANK PLC",
    "bankCode": "232",
    "sortCode": "000001",
  },
  {
    "214": "First City Monument Bank",
    "bankName": "First City Monument Bank",
    "bankCode": "214",
    "sortCode": "000003",
  },
  {
    "011": "FIRST BANK OF NIGERIA PLC",
    "bankName": "FIRST BANK OF NIGERIA PLC",
    "bankCode": "011",
    "sortCode": "000016",
  },
  {
    "023": "Citibank Nigeria LTD",
    "bankName": "Citibank Nigeria LTD",
    "bankCode": "023",
    "sortCode": "000009",
  },
  {
    "084": "ENTERPRISE BANK LTD",
    "bankName": "ENTERPRISE BANK LTD",
    "bankCode": "084",
    "sortCode": "000019",
  },
  {
    "030": "Heritage Bank",
    "bankName": "HERITAGE BANK",
    "bankCode": "030",
    "sortCode": "000020",
  },
  {
    "032": "UNION BANK OF NIGERIA PLC",
    "bankName": "UNION BANK OF NIGERIA PLC",
    "bankCode": "032",
    "sortCode": "000018",
  },
  {
    "033": "UNITED BANK FOR AFRICA",
    "bankName": "UNITED BANK FOR AFRICA PLC",
    "bankCode": "033",
    "sortCode": "000004",
  },
  {
    "035": "Wema Bank PLC",
    "bankName": "WEMA BANK PLC",
    "bankCode": "035",
    "sortCode": "000017",
  },
  {
    "323": "Access Mobile",
    "bankName": "Access Mobile",
    "bankCode": "323",
    "sortCode": "100013",
  },
  {
    "322": "ZenithMobile",
    "bankName": "ZenithMobile",
    "bankCode": "322",
    "sortCode": "100018",
  },
  {
    "044": "ACCESS BANK PLC",
    "bankName": "ACCESS BANK PLC",
    "bankCode": "044",
    "sortCode": "000014", 
  },
  {
    "050": "ECOBANK NIGERIA PLC",
    "bankName": "ECOBANK NIGERIA PLC",
    "bankCode": "050",
    "sortCode": "000010",
  },
  {
    "057": "Zenith Bank PLC",
    "bankName": "ZENITH BANK PLC",
    "bankCode": "057",
    "sortCode": "000015"
  },
  {
    "058": "Guaranty Trust Bank",
    "bankName": "Guaranty Trust Bank PLC",
    "bankCode": "058",
    "sortCode": "000013",
  },
  {
    "063": "ACCESS BANK PLC (DIAMOND)",
    "bankName": "ACCESS BANK PLC (DIAMOND)",
    "bankCode": "063",
    "sortCode": "000005",
  },
  {
    "315": "GTMobile",
    "bankName": "GTMobile",
    "bankCode": "315",
    "sortCode": "100009",
  },
  {
    "068": "STANDARD CHARTERED BANK NIGERIA LTD",
    "bankName": "STANDARD CHARTERED BANK NIGERIA LTD",
    "bankCode": "068",
    "sortCode": "000021",
  },
  {
    "601": "FSDH Merchant Bank",
    "bankName": "FSDH MERCHANT BANK LIMITED",
    "bankCode": "601",
    "sortCode": "400001",
  },
  {
    "311": "Parkway-ReadyCash",
    "bankName": "Parkway-ReadyCash",
    "bankCode": "311",
    "sortCode": "100003",
  },
  {
    "304": "StanbicMobileMoney (easewallet)",
    "bankName": "StanbicMobileMoney (easewallet)",
    "bankCode": "304",
    "sortCode": "100007",
  },
  {
    "014": "MAINSTREET MICROFINANCE BANK",
    "bankName": "MAINSTREET MICROFINANCE BANK",
    "bankCode": "014",
    "sortCode": "090171",
  },
  {
    "070": "FIDELITY BANK PLC",    
    "bankName": "FIDELITY BANK PLC",
    "bankCode": "070",
    "sortCode": "000007",
  },
  {
    "076": "POLARIS BANK LTD (SKYE BANK PLC)",
    "bankName": "POLARIS BANK LTD (SKYE BANK PLC)",
    "bankCode": "076",
    "sortCode": "000008",
  },
  {
    "082": "Keystone Bank",
    "bankName": "KEYSTONE BANK",
    "bankCode": "082",
    "sortCode": "000002",
  },
  {
    "401": "ASO SAVINGS AND LOANS",
    "bankName": "ASO SAVINGS AND LOANS",
    "bankCode": "401",
    "sortCode": "090001",
  },
  {
    "526": "Parralex Microfinance bank",
    "bankName": "Parralex Microfinance bank",
    "bankCode": "526",
    "sortCode": "090004",
  },
  {
    "301": "JAIZ Bank",
    "bankName": "JAIZ BANK PLC",
    "bankCode": "301",
    "sortCode": "000006",
  },
  {
    "305": "PAYCOM (OPAY)",
    "bankName": "PAYCOM (OPAY)",
    "bankCode": "305",
    "sortCode": "100004",
  },
  {
    "307": "EcoMobile",
    "bankName": "EcoMobile",
    "bankCode": "307",
    "sortCode": "100030",
  },
  {
    "215": "UNITY BANK",
    "bankName": "UNITY BANK PLC",
    "bankCode": "215",
    "sortCode": "000011",
  },
  {
    "309": "FBNMobile",
    "bankName":  "FBNMobile",
    "bankCode": "309",
    "sortCode": "100014",
  },
  {
    "221": "STANBIC IBTC BANK PLC",
    "bankName": "STANBIC IBTC BANK PLC",
    "bankCode": "221",
    "sortCode": "000012",
  },
  {
    "101": "Providus Bank",
    "bankName": "PROVIDUS BANK",
    "bankCode": "101",
    "sortCode": "000023",
  },
];
