// @flow

import { AccessControl } from 'accesscontrol';
import { rolesType } from '../enumType';

const ac = new AccessControl();

export default (() => {
  ac.grant(rolesType.USER)
    .readOwn('User')
    .updateOwn('User')
    .readAny('Wallet')
    .updateOwn('Wallet')
    .readOwn('Transaction')
    .createAny('Transaction')
    .readOwn('CommissionWallet')
    .readOwn('CommissionHistory')
    .createOwn('CommissionHistory')
    .createOwn('Issues')
    .readOwn('Issues')
    .readOwn('Referral')
    .readOwn('Beneficiary')
    .readOwn('PaymentSecret')
    .readAny('AppUpdate')
    .readOwn('Message')

  ac.grant(rolesType.AGENT)
    .extend(rolesType.USER)

  ac.grant(rolesType.SUPERAGENT)
    .extend(rolesType.USER)
    .extend(rolesType.AGENT)

  ac.grant(rolesType.SUPPORT)
    .extend(rolesType.USER)
    .readAny('User')
    .readAny('User')
    .updateAny('User')
    .createAny('User')
    .readAny('Wallet')
    .readAny('ServiceSwitch')
    .readAny('Transaction')
    .readAny('CommissionWallet')
    .readAny('CommissionHistory')
    .readAny('AuthOtpVerify')
    .updateAny('AuthOtpVerify')
    .readAny('Issues')
    .updateAny('Issues')
    .readAny('Referral')
    .readAny('Beneficiary')
    .updateAny('Beneficiary')
    .readAny('Message')
    .readAny('AgentRequest')
    .readAny('PosTerminal')
    .readAny('CacheBvn')
    .readAny('PaymentNotification')
    .readAny('PosNotification')

  ac.grant(rolesType.ADMIN)
    .extend(rolesType.SUPPORT)
    .updateAny('Wallet')
    .updateAny('ServiceSwitch')
    .updateAny('Transaction')
    .updateAny('CommissionWallet')
    .updateAny('CommissionHistory')
    .readAny('ServiceSwitchLog')
    .createAny('Message')
    .updateAny('Message')
    .deleteAny('Message')
    .updateAny('AgentRequest')
    .updateAny('PosTerminal')

  ac.grant(rolesType.SUPERADMIN)
    .extend(rolesType.USER)
    .extend(rolesType.SUPPORT)
    .extend(rolesType.ADMIN)
    .createAny('ServiceSwitch')
    .deleteAny('user')
    .deleteAny('Wallet')
    .deleteAny('Transaction')
    .deleteAny('AuthOtpVerify')
    .deleteAny('Issues')
    .deleteAny('Beneficiary')
    .updateAny('PaymentSecret')
    .updateAny('AppUpdate')
    .createAny('AppUpdate')
    .deleteAny('AppUpdate')
    .createAny('PosTerminal')
    .deleteAny('PosTerminal')

  return ac;
})();
