// @flow
import dotenv from "dotenv";

// Load .env
dotenv.config();

export const {
  NODE_ENV,
  PORT,
  WORKER_PORT, //note ??
  HOST_NAME,
  WORKER_API_BASE_URI,
  API_SCHEME,
  SWAGGER_DOMAIN,
  LOGS_DBURL,
  DBURL,
  JWT_SECRET,
  JWT_BEARER,
  JWT_EXPIRATION_MINUTES,
  SENTRY_KEY,
  SENTRY_ID,
  SENDGRIDAPIKEY,
  MAILER_FROM_OPTION,
  BULK_SMS_NG_URL,
  BULK_SMS_PASS,
  BULK_SMS_SENDER,
  BULK_SMS_USERNAME,

  MONNIFY_API_KEY,
  MONNIFY_CLIENT_SECRET_KEY,
  MONNIFY_BASE_URL,

  PAYSTACK_SECRET_KEY,
  PAYSTACK_API_URL,


  AGENT_COUNTER,
  VEND_HOST,
  VEND_USERNAME,
  VEND_PASSWORD,
  VEND_HASH,

  GLADE_MERCHANT_ID,
  GLADE_MERCHANT_KEY,
  GLADE_ENDPOINT,

  PRIME_AIRTIME_URL,
  PRIME_AIRTIME_USERNAME,
  PRIME_AIRTIME_PASSWORD,


  VTPASS_URL,
  VTPASS_USERNAME,
  VTPASS_PASSWORD,

  SMART_SMS_TOKEN,
  SMART_SMS_URL,

  DYNO_URL,

  TERMI_BASE_URL,
  TERMI_API_KEY,

  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_BUCKET_REGION,
  AWS_SES_CONFIG_SET,

  LOGS_MAIL,

  RUBIES_LIVE_URL,
  RUBIES_LIVE_SK,
  RUBIES_DR_ACCOUNTNAME,
} = process.env;
