version: '3'
services:
  worker:
    build:
      dockerfile: Dockerfile
      context: .
    # links:
    #   - api
    ports:
      - "8008:8008"
    volumes:
      - /usr/apps/node_modules
      - .:/usr/apps
    env_file:
      - ./.env
    environment: 
      - NODE_ENV=${NODE_ENV}
      - WORKER_PORT=${WORKER_PORT}
      - HOST_NAME=http://api
      - WORKER_API_BASE_URI=${WORKER_API_BASE_URI}
      - API_SCHEME=${API_SCHEME}
      - SWAGGER_DOMAIN=api
      - LOGS_DBURL=${LOGS_DBURL}
      - DBURL=${DBURL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_BEARER=${JWT_BEARER}
      - JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES}
      - SENTRY_KEY=${SENTRY_KEY}
      - SENTRY_ID=${SENTRY_ID}
      - SENDGRIDAPIKEY=${SENDGRIDAPIKEY}
      - MAILER_FROM_OPTION=${MAILER_FROM_OPTION}
      - BULK_SMS_NG_URL=${BULK_SMS_NG_URL}
      - BULK_SMS_PASS=${BULK_SMS_PASS}
      - BULK_SMS_SENDER=${BULK_SMS_SENDER}
      - BULK_SMS_USERNAME=${BULK_SMS_USERNAME}
      - MONNIFY_API_KEY=${MONNIFY_API_KEY}
      - MONNIFY_CLIENT_SECRET_KEY=${MONNIFY_CLIENT_SECRET_KEY}
      - MONNIFY_BASE_URL=${MONNIFY_BASE_URL}
      - PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
      - PAYSTACK_API_URL=${PAYSTACK_API_URL}
      - AGENT_COUNTER=${AGENT_COUNTER}
      - VEND_HOST=${VEND_HOST}
      - VEND_USERNAME=${VEND_USERNAME}
      - VEND_PASSWORD=${VEND_PASSWORD}
      - VEND_HASH=${VEND_HASH}
      - GLADE_MERCHANT_ID=${GLADE_MERCHANT_ID}
      - GLADE_MERCHANT_KEY=${GLADE_MERCHANT_KEY}
      - GLADE_ENDPOINT=${GLADE_ENDPOINT}
      - PRIME_AIRTIME_URL=${PRIME_AIRTIME_URL}
      - PRIME_AIRTIME_USERNAME=${PRIME_AIRTIME_USERNAME}
      - PRIME_AIRTIME_PASSWORD=${PRIME_AIRTIME_PASSWORD}
      - VTPASS_URL=${VTPASS_URL}
      - VTPASS_USERNAME=${VTPASS_USERNAME}
      - VTPASS_PASSWORD=${VTPASS_PASSWORD}
      - SMART_SMS_TOKEN=${SMART_SMS_TOKEN}
      - SMART_SMS_URL=${SMART_SMS_URL}
      - DYNO_URL=${DYNO_URL}